//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketSalesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhKhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuongTrinhKhuyenMai()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaCT { get; set; }
        public string TenCT { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> GiaKhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
