//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketSalesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenXe()
        {
            this.VeXes = new HashSet<VeXe>();
            this.XE_CHUYENXE = new HashSet<XE_CHUYENXE>();
        }
    
        public string MaChuyen { get; set; }
        public string TenChuyen { get; set; }
        public Nullable<System.DateTime> NgayGioKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayGioDen { get; set; }
        public string MaTuyen { get; set; }
    
        public virtual TuyenXe TuyenXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeXe> VeXes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XE_CHUYENXE> XE_CHUYENXE { get; set; }
    }
}
