//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketSalesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.VeXes = new HashSet<VeXe>();
        }
    
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayGioTaoHoaDon { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int MaNV { get; set; }
        public int MaKH { get; set; }
        public string MaCT { get; set; }
    
        public virtual ChuongTrinhKhuyenMai ChuongTrinhKhuyenMai { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeXe> VeXes { get; set; }
    }
}
