//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketSalesWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;

    
    public partial class QLBANVEXEEntities5 : DbContext
    {
        public QLBANVEXEEntities5()
            : base("name=QLBANVEXEEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuongTrinhKhuyenMai> ChuongTrinhKhuyenMais { get; set; }
        public virtual DbSet<ChuyenXe> ChuyenXes { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TuyenXe> TuyenXes { get; set; }
        public virtual DbSet<VeXe> VeXes { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<XE_CHUYENXE> XE_CHUYENXE { get; set; }
    
        public virtual int sp_DeleteChuongTrinhKhuyenMai(string maCT)
        {
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteChuongTrinhKhuyenMai", maCTParameter);
        }
    
        public virtual int sp_DeleteChuyenXe(string maChuyen)
        {
            var maChuyenParameter = maChuyen != null ?
                new ObjectParameter("MaChuyen", maChuyen) :
                new ObjectParameter("MaChuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteChuyenXe", maChuyenParameter);
        }
    
        public virtual int sp_DeleteGhe(string maGhe)
        {
            var maGheParameter = maGhe != null ?
                new ObjectParameter("MaGhe", maGhe) :
                new ObjectParameter("MaGhe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteGhe", maGheParameter);
        }
    
        public virtual int sp_DeleteHoaDon(string maHoaDon)
        {
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteHoaDon", maHoaDonParameter);
        }
    
        public virtual int sp_DeleteKhachHang(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteKhachHang", maKHParameter);
        }
    
        public virtual int sp_DeleteNhanVien(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteNhanVien", maNVParameter);
        }
    
        public virtual int sp_DeletePhongBan(string maPB)
        {
            var maPBParameter = maPB != null ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeletePhongBan", maPBParameter);
        }
    
        public virtual int sp_DeleteTaiKhoan(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteTaiKhoan", idParameter);
        }
    
        public virtual int sp_DeleteTuyenXe(string maTuyen)
        {
            var maTuyenParameter = maTuyen != null ?
                new ObjectParameter("MaTuyen", maTuyen) :
                new ObjectParameter("MaTuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteTuyenXe", maTuyenParameter);
        }
    
        public virtual int sp_DeleteVeXe(string maVe)
        {
            var maVeParameter = maVe != null ?
                new ObjectParameter("MaVe", maVe) :
                new ObjectParameter("MaVe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteVeXe", maVeParameter);
        }
    
        public virtual int sp_DeleteXe(string maXe)
        {
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteXe", maXeParameter);
        }
    
        public virtual int sp_DeleteXE_CHUYENXE(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteXE_CHUYENXE", idParameter);
        }
    
        public virtual int sp_InsertChuongTrinhKhuyenMai(string maCT, string tenCT, string noiDung, Nullable<int> giaKhuyenMai, Nullable<System.DateTime> ngayKT, Nullable<System.DateTime> ngayBD)
        {
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            var tenCTParameter = tenCT != null ?
                new ObjectParameter("TenCT", tenCT) :
                new ObjectParameter("TenCT", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var giaKhuyenMaiParameter = giaKhuyenMai.HasValue ?
                new ObjectParameter("GiaKhuyenMai", giaKhuyenMai) :
                new ObjectParameter("GiaKhuyenMai", typeof(int));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertChuongTrinhKhuyenMai", maCTParameter, tenCTParameter, noiDungParameter, giaKhuyenMaiParameter, ngayKTParameter, ngayBDParameter);
        }
    
        public virtual int sp_InsertChuyenXe(string maChuyen, string tenChuyen, Nullable<System.DateTime> ngayGioKhoiHanh, Nullable<System.DateTime> ngayGioDen, string maTuyen)
        {
            var maChuyenParameter = maChuyen != null ?
                new ObjectParameter("MaChuyen", maChuyen) :
                new ObjectParameter("MaChuyen", typeof(string));
    
            var tenChuyenParameter = tenChuyen != null ?
                new ObjectParameter("TenChuyen", tenChuyen) :
                new ObjectParameter("TenChuyen", typeof(string));
    
            var ngayGioKhoiHanhParameter = ngayGioKhoiHanh.HasValue ?
                new ObjectParameter("NgayGioKhoiHanh", ngayGioKhoiHanh) :
                new ObjectParameter("NgayGioKhoiHanh", typeof(System.DateTime));
    
            var ngayGioDenParameter = ngayGioDen.HasValue ?
                new ObjectParameter("NgayGioDen", ngayGioDen) :
                new ObjectParameter("NgayGioDen", typeof(System.DateTime));
    
            var maTuyenParameter = maTuyen != null ?
                new ObjectParameter("MaTuyen", maTuyen) :
                new ObjectParameter("MaTuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertChuyenXe", maChuyenParameter, tenChuyenParameter, ngayGioKhoiHanhParameter, ngayGioDenParameter, maTuyenParameter);
        }
    
        public virtual int sp_InsertGhe(string maGhe, string tenGhe, Nullable<byte> trangThai, string maXe)
        {
            var maGheParameter = maGhe != null ?
                new ObjectParameter("MaGhe", maGhe) :
                new ObjectParameter("MaGhe", typeof(string));
    
            var tenGheParameter = tenGhe != null ?
                new ObjectParameter("TenGhe", tenGhe) :
                new ObjectParameter("TenGhe", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(byte));
    
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertGhe", maGheParameter, tenGheParameter, trangThaiParameter, maXeParameter);
        }
    
        public virtual int sp_InsertHoaDon(string maHoaDon, Nullable<System.DateTime> ngayGioTaoHoaDon, Nullable<int> tongTien, string maNV, string maKH, string maCT)
        {
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            var ngayGioTaoHoaDonParameter = ngayGioTaoHoaDon.HasValue ?
                new ObjectParameter("NgayGioTaoHoaDon", ngayGioTaoHoaDon) :
                new ObjectParameter("NgayGioTaoHoaDon", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(int));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertHoaDon", maHoaDonParameter, ngayGioTaoHoaDonParameter, tongTienParameter, maNVParameter, maKHParameter, maCTParameter);
        }
    
        public virtual int sp_InsertKhachHang(string maKH, string tenKH, Nullable<byte> gioi_Tinh, Nullable<System.DateTime> ngay_Sinh, Nullable<int> id)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var gioi_TinhParameter = gioi_Tinh.HasValue ?
                new ObjectParameter("Gioi_Tinh", gioi_Tinh) :
                new ObjectParameter("Gioi_Tinh", typeof(byte));
    
            var ngay_SinhParameter = ngay_Sinh.HasValue ?
                new ObjectParameter("Ngay_Sinh", ngay_Sinh) :
                new ObjectParameter("Ngay_Sinh", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertKhachHang", maKHParameter, tenKHParameter, gioi_TinhParameter, ngay_SinhParameter, idParameter);
        }
    
        public virtual int sp_InsertNhanVien(string maNV, string tenNV, string chucVu, Nullable<System.DateTime> ngayVaoLam, Nullable<byte> gioi_Tinh, Nullable<System.DateTime> ngay_Sinh, string maPB, Nullable<int> id)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var gioi_TinhParameter = gioi_Tinh.HasValue ?
                new ObjectParameter("Gioi_Tinh", gioi_Tinh) :
                new ObjectParameter("Gioi_Tinh", typeof(byte));
    
            var ngay_SinhParameter = ngay_Sinh.HasValue ?
                new ObjectParameter("Ngay_Sinh", ngay_Sinh) :
                new ObjectParameter("Ngay_Sinh", typeof(System.DateTime));
    
            var maPBParameter = maPB != null ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNhanVien", maNVParameter, tenNVParameter, chucVuParameter, ngayVaoLamParameter, gioi_TinhParameter, ngay_SinhParameter, maPBParameter, idParameter);
        }
    
        public virtual int sp_InsertPhongBan(string maPB, string tenPB)
        {
            var maPBParameter = maPB != null ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(string));
    
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertPhongBan", maPBParameter, tenPBParameter);
        }
    
        public virtual int sp_InsertTaiKhoan(string email, string matKhau, Nullable<byte> vaiTro, string sdt)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var vaiTroParameter = vaiTro.HasValue ?
                new ObjectParameter("VaiTro", vaiTro) :
                new ObjectParameter("VaiTro", typeof(byte));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertTaiKhoan", emailParameter, matKhauParameter, vaiTroParameter, sdtParameter);
        }
    
        public virtual int sp_InsertTuyenXe(string maTuyen, string tenTuyen)
        {
            var maTuyenParameter = maTuyen != null ?
                new ObjectParameter("MaTuyen", maTuyen) :
                new ObjectParameter("MaTuyen", typeof(string));
    
            var tenTuyenParameter = tenTuyen != null ?
                new ObjectParameter("TenTuyen", tenTuyen) :
                new ObjectParameter("TenTuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertTuyenXe", maTuyenParameter, tenTuyenParameter);
        }
    
        public virtual int sp_InsertVeXe(string maVe, Nullable<int> gia, string quyDinh, Nullable<System.DateTime> ngayXuatVe, string maHoaDon, string maGhe, string maChuyen)
        {
            var maVeParameter = maVe != null ?
                new ObjectParameter("MaVe", maVe) :
                new ObjectParameter("MaVe", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(int));
    
            var quyDinhParameter = quyDinh != null ?
                new ObjectParameter("QuyDinh", quyDinh) :
                new ObjectParameter("QuyDinh", typeof(string));
    
            var ngayXuatVeParameter = ngayXuatVe.HasValue ?
                new ObjectParameter("NgayXuatVe", ngayXuatVe) :
                new ObjectParameter("NgayXuatVe", typeof(System.DateTime));
    
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            var maGheParameter = maGhe != null ?
                new ObjectParameter("MaGhe", maGhe) :
                new ObjectParameter("MaGhe", typeof(string));
    
            var maChuyenParameter = maChuyen != null ?
                new ObjectParameter("MaChuyen", maChuyen) :
                new ObjectParameter("MaChuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertVeXe", maVeParameter, giaParameter, quyDinhParameter, ngayXuatVeParameter, maHoaDonParameter, maGheParameter, maChuyenParameter);
        }
    
        public virtual int sp_InsertXe(string maXe, string tenXe, Nullable<byte> loaiXe, Nullable<int> sLGhe)
        {
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            var tenXeParameter = tenXe != null ?
                new ObjectParameter("TenXe", tenXe) :
                new ObjectParameter("TenXe", typeof(string));
    
            var loaiXeParameter = loaiXe.HasValue ?
                new ObjectParameter("LoaiXe", loaiXe) :
                new ObjectParameter("LoaiXe", typeof(byte));
    
            var sLGheParameter = sLGhe.HasValue ?
                new ObjectParameter("SLGhe", sLGhe) :
                new ObjectParameter("SLGhe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertXe", maXeParameter, tenXeParameter, loaiXeParameter, sLGheParameter);
        }
    
        public virtual int sp_InsertXE_CHUYENXE(string maChuyen, string maXe)
        {
            var maChuyenParameter = maChuyen != null ?
                new ObjectParameter("MaChuyen", maChuyen) :
                new ObjectParameter("MaChuyen", typeof(string));
    
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertXE_CHUYENXE", maChuyenParameter, maXeParameter);
        }
    
        public virtual int sp_UpdateChuongTrinhKhuyenMai(string maCT, string tenCT, string noiDung, Nullable<int> giaKhuyenMai, Nullable<System.DateTime> ngayKT, Nullable<System.DateTime> ngayBD)
        {
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            var tenCTParameter = tenCT != null ?
                new ObjectParameter("TenCT", tenCT) :
                new ObjectParameter("TenCT", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var giaKhuyenMaiParameter = giaKhuyenMai.HasValue ?
                new ObjectParameter("GiaKhuyenMai", giaKhuyenMai) :
                new ObjectParameter("GiaKhuyenMai", typeof(int));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateChuongTrinhKhuyenMai", maCTParameter, tenCTParameter, noiDungParameter, giaKhuyenMaiParameter, ngayKTParameter, ngayBDParameter);
        }
    
        public virtual int sp_UpdateChuyenXe(string maChuyen, string tenChuyen, Nullable<System.DateTime> ngayGioKhoiHanh, Nullable<System.DateTime> ngayGioDen, string maTuyen)
        {
            var maChuyenParameter = maChuyen != null ?
                new ObjectParameter("MaChuyen", maChuyen) :
                new ObjectParameter("MaChuyen", typeof(string));
    
            var tenChuyenParameter = tenChuyen != null ?
                new ObjectParameter("TenChuyen", tenChuyen) :
                new ObjectParameter("TenChuyen", typeof(string));
    
            var ngayGioKhoiHanhParameter = ngayGioKhoiHanh.HasValue ?
                new ObjectParameter("NgayGioKhoiHanh", ngayGioKhoiHanh) :
                new ObjectParameter("NgayGioKhoiHanh", typeof(System.DateTime));
    
            var ngayGioDenParameter = ngayGioDen.HasValue ?
                new ObjectParameter("NgayGioDen", ngayGioDen) :
                new ObjectParameter("NgayGioDen", typeof(System.DateTime));
    
            var maTuyenParameter = maTuyen != null ?
                new ObjectParameter("MaTuyen", maTuyen) :
                new ObjectParameter("MaTuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateChuyenXe", maChuyenParameter, tenChuyenParameter, ngayGioKhoiHanhParameter, ngayGioDenParameter, maTuyenParameter);
        }
    
        public virtual int sp_UpdateGhe(string maGhe, string tenGhe, Nullable<byte> trangThai, string maXe)
        {
            var maGheParameter = maGhe != null ?
                new ObjectParameter("MaGhe", maGhe) :
                new ObjectParameter("MaGhe", typeof(string));
    
            var tenGheParameter = tenGhe != null ?
                new ObjectParameter("TenGhe", tenGhe) :
                new ObjectParameter("TenGhe", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(byte));
    
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateGhe", maGheParameter, tenGheParameter, trangThaiParameter, maXeParameter);
        }
    
        public virtual int sp_UpdateHoaDon(string maHoaDon, Nullable<System.DateTime> ngayGioTaoHoaDon, Nullable<int> tongTien, string maNV, string maKH, string maCT)
        {
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            var ngayGioTaoHoaDonParameter = ngayGioTaoHoaDon.HasValue ?
                new ObjectParameter("NgayGioTaoHoaDon", ngayGioTaoHoaDon) :
                new ObjectParameter("NgayGioTaoHoaDon", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(int));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateHoaDon", maHoaDonParameter, ngayGioTaoHoaDonParameter, tongTienParameter, maNVParameter, maKHParameter, maCTParameter);
        }
    
        public virtual int sp_UpdateKhachHang(string maKH, string tenKH, Nullable<byte> gioi_Tinh, Nullable<System.DateTime> ngay_Sinh, Nullable<int> id)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var gioi_TinhParameter = gioi_Tinh.HasValue ?
                new ObjectParameter("Gioi_Tinh", gioi_Tinh) :
                new ObjectParameter("Gioi_Tinh", typeof(byte));
    
            var ngay_SinhParameter = ngay_Sinh.HasValue ?
                new ObjectParameter("Ngay_Sinh", ngay_Sinh) :
                new ObjectParameter("Ngay_Sinh", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateKhachHang", maKHParameter, tenKHParameter, gioi_TinhParameter, ngay_SinhParameter, idParameter);
        }
    
        public virtual int sp_UpdateNhanVien(string maNV, string tenNV, string chucVu, Nullable<System.DateTime> ngayVaoLam, Nullable<byte> gioi_Tinh, Nullable<System.DateTime> ngay_Sinh, string maPB, Nullable<int> id)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var gioi_TinhParameter = gioi_Tinh.HasValue ?
                new ObjectParameter("Gioi_Tinh", gioi_Tinh) :
                new ObjectParameter("Gioi_Tinh", typeof(byte));
    
            var ngay_SinhParameter = ngay_Sinh.HasValue ?
                new ObjectParameter("Ngay_Sinh", ngay_Sinh) :
                new ObjectParameter("Ngay_Sinh", typeof(System.DateTime));
    
            var maPBParameter = maPB != null ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateNhanVien", maNVParameter, tenNVParameter, chucVuParameter, ngayVaoLamParameter, gioi_TinhParameter, ngay_SinhParameter, maPBParameter, idParameter);
        }
    
        public virtual int sp_UpdatePhongBan(string maPB, string tenPB)
        {
            var maPBParameter = maPB != null ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(string));
    
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePhongBan", maPBParameter, tenPBParameter);
        }
    
        public virtual int sp_UpdateTaiKhoan(Nullable<int> id, string email, string matKhau, Nullable<byte> vaiTro, string sdt)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var vaiTroParameter = vaiTro.HasValue ?
                new ObjectParameter("VaiTro", vaiTro) :
                new ObjectParameter("VaiTro", typeof(byte));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateTaiKhoan", idParameter, emailParameter, matKhauParameter, vaiTroParameter, sdtParameter);
        }
    
        public virtual int sp_UpdateTuyenXe(string maTuyen, string tenTuyen)
        {
            var maTuyenParameter = maTuyen != null ?
                new ObjectParameter("MaTuyen", maTuyen) :
                new ObjectParameter("MaTuyen", typeof(string));
    
            var tenTuyenParameter = tenTuyen != null ?
                new ObjectParameter("TenTuyen", tenTuyen) :
                new ObjectParameter("TenTuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateTuyenXe", maTuyenParameter, tenTuyenParameter);
        }
    
        public virtual int sp_UpdateVeXe(string maVe, Nullable<int> gia, string quyDinh, Nullable<System.DateTime> ngayXuatVe, string maHoaDon, string maGhe, string maChuyen)
        {
            var maVeParameter = maVe != null ?
                new ObjectParameter("MaVe", maVe) :
                new ObjectParameter("MaVe", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(int));
    
            var quyDinhParameter = quyDinh != null ?
                new ObjectParameter("QuyDinh", quyDinh) :
                new ObjectParameter("QuyDinh", typeof(string));
    
            var ngayXuatVeParameter = ngayXuatVe.HasValue ?
                new ObjectParameter("NgayXuatVe", ngayXuatVe) :
                new ObjectParameter("NgayXuatVe", typeof(System.DateTime));
    
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            var maGheParameter = maGhe != null ?
                new ObjectParameter("MaGhe", maGhe) :
                new ObjectParameter("MaGhe", typeof(string));
    
            var maChuyenParameter = maChuyen != null ?
                new ObjectParameter("MaChuyen", maChuyen) :
                new ObjectParameter("MaChuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateVeXe", maVeParameter, giaParameter, quyDinhParameter, ngayXuatVeParameter, maHoaDonParameter, maGheParameter, maChuyenParameter);
        }
    
        public virtual int sp_UpdateXe(string maXe, string tenXe, Nullable<byte> loaiXe, Nullable<int> sLGhe)
        {
            var maXeParameter = maXe != null ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(string));
    
            var tenXeParameter = tenXe != null ?
                new ObjectParameter("TenXe", tenXe) :
                new ObjectParameter("TenXe", typeof(string));
    
            var loaiXeParameter = loaiXe.HasValue ?
                new ObjectParameter("LoaiXe", loaiXe) :
                new ObjectParameter("LoaiXe", typeof(byte));
    
            var sLGheParameter = sLGhe.HasValue ?
                new ObjectParameter("SLGhe", sLGhe) :
                new ObjectParameter("SLGhe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateXe", maXeParameter, tenXeParameter, loaiXeParameter, sLGheParameter);
        }
    }
}
