//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketSalesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeXe
    {
        public string MaVe { get; set; }
        public Nullable<int> Gia { get; set; }
        public string QuyDinh { get; set; }
        public Nullable<System.DateTime> NgayXuatVe { get; set; }
        public string MaHoaDon { get; set; }
        public string MaGhe { get; set; }
        public string MaChuyen { get; set; }
    
        public virtual ChuyenXe ChuyenXe { get; set; }
        public virtual Ghe Ghe { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
