//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketSalesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE_CHUYENXE
    {
        public int Id { get; set; }
        public string MaChuyen { get; set; }
        public string MaXe { get; set; }
    
        public virtual ChuyenXe ChuyenXe { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
